spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  jwt:
    secret: hesukey
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/websocket
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        # show_sql: true
#        format_sql: true
#
#logging.level:
#  org.hibernate.SQL: debug
  # org.hibernate.type: trace
#server:
#  port: 8081